[custom.tztime]
command = 'date +"%a %b %d %R:%S"'
when = "false"
format = '[\[$symbol($output)\]](green)'

[azure]
disabled = true
format = 'on [($subscription)]($style) '
style = 'blue bold'

[azure.subscription_aliases]
'jamilshaikh07' = 'PersonalAzure'

[git_status]
conflicted = 'ğŸ³'
ahead = 'ğŸğŸ’¨'
behind = 'ğŸ˜°'
diverged = 'ğŸ˜µ'
up_to_date = 'âœ“'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'

[git_commit]
commit_hash_length = 4
tag_symbol = 'ğŸ”– '

[git_branch]
symbol = 'ğŸŒ± '
ignore_branches = ['master', 'main']

[directory]
truncation_length = 3
truncation_symbol = '../'

[helm]
format = 'via [âˆ $version](bold white) '

[kubernetes]
format = '[k8s $context\($namespace\)](green) '
disabled = false

[kubernetes.context_aliases]

[kubernetes.user_aliases]

[terraform]
format = '[tf $workspace]($style) '

[python]
disabled = true

# ~/.config/starship.toml

[aws]
format = 'aws [$symbol($profile )(\($region\) )]($style)'
style = 'bold green'
symbol = 'ğŸ…° '
[aws.region_aliases]
us-east-1 = 'va'
[aws.profile_aliases]
CompanyGroupFrobozzOnCallAccess = 'Frobozz'


[gcloud]
symbol = 'ï¸ğŸ‡¬ï¸ '
format = 'on [$symbol$account (\($project\))]($style) '
style = 'bold yellow'

[gcloud.region_aliases]
account = 'jamil'
us-central1 = 'uc1'

[gcloud.project_aliases]
beamer-staging = 'STG'
getbeamer = 'PROD'
