# [custom.tztime]
# command = 'date +"%a %b %d %R:%S"'
# when = "false"
# format = '[\[$symbol($output)\]](green)'

[azure]
disabled = true
format = 'on [($subscription)]($style) '
style = 'blue bold'

[azure.subscription_aliases]
'jamilshaikh07' = 'PersonalAzure'

[git_status]
conflicted = 'üè≥'
ahead = 'üèéüí®'
behind = 'üò∞'
diverged = 'üòµ'
up_to_date = '‚úì'
untracked = 'ü§∑'
stashed = 'üì¶'
modified = 'üìù'
staged = '[++\($count\)](green)'
renamed = 'üëÖ'
deleted = 'üóë'

[git_commit]
commit_hash_length = 4
tag_symbol = 'üîñ '

[git_branch]
symbol = 'üå± '
ignore_branches = ['master', 'main']

[directory]
truncation_length = 3
truncation_symbol = '../'

[helm]
format = 'via [‚éà $version](bold white) '
#
# [kubernetes]
# format = '[k8s $context\($namespace\)](green) '
# disabled = false
#
# [kubernetes.context_aliases]
#
# [kubernetes.user_aliases]
[custom.k8s]
command = 'kubectl config current-context 2>/dev/null'
when = 'test -n "$KUBECONFIG"'
shell = ['bash', '-lc']
symbol = 'k8s'
style = 'bold green'
format = '[$symbol $output]($style) '

[terraform]
format = '[tf $workspace]($style) '

[python]
disabled = true

[aws]
format = 'aws [$symbol($profile )(\($region\) )]($style)'
style = 'bold green'
symbol = 'üÖ∞ '
[aws.region_aliases]
us-east-1 = 'va'
[aws.profile_aliases]
CompanyGroupFrobozzOnCallAccess = 'Frobozz'


[gcloud]
symbol = 'Ô∏èüá¨Ô∏è '
format = 'on [$symbol$account (\($project\))]($style) '
style = 'bold yellow'

[gcloud.region_aliases]
account = 'jamil'
us-east1 = 'ue1'

[gcloud.project_aliases]
beamer-staging = 'STG'
getbeamer = 'PROD'
